### ISSUE TITLE
[aws-roll-keys.py] encryption fails while using a special characters 

### ISSUE THREAD

**Issue by snieg** [bartekj/aws-tools#22]
Encryption of rolled keys with fails if you have a special character in your GPG key:

`DEBUG:gnupg:Âniegocki <xxx@metalcore.pl>: skipped: No public key                                            
DEBUG:gnupg:[GNUPG:] INV_RECP 1 Piotr Ã                                                                                    
DEBUG:gnupg:Âniegocki <xxx@metalcore.pl>                                                                       
DEBUG:gnupg:[GNUPG:] FAILURE encrypt 9                                                                                     
DEBUG:gnupg:gpg: [stdin]: encryption failed: No public key` 

Adding **gpg.encoding = 'utf-8'** resolves the issue. 

gpg.list_keys output without gpg.encoding = 'utf-8':

```
#!/usr/bin/python3
import gnupg

gpg = gnupg.GPG(use_agent=True)

private_keys = gpg.list_keys(True)
print(private_keys[0]["uids"][1])
```
```
$ ./gpg.py 
Piotr Åniegocki <xxx@metalcore.pl>
```
Fixed gpg.list_keys output:

```#!/usr/bin/python3
import gnupg

gpg = gnupg.GPG(use_agent=True)

gpg.encoding = 'utf-8'

private_keys = gpg.list_keys(True)
print(private_keys[0]["uids"][1])
```

```
$ ./gpg.py 
Piotr Śniegocki <xxx@metalcore.pl>
```

**Comment by bartekj** [comment]
Good stuff, issue was found and resolved in #23
